name: "MWA- Daily Build"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
  schedule:
    - cron: '0 12 * * *'

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

concurrency: integration_testing
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:1.5.1
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      IS_RUN_AS_SERVICEPRINCIPAL: true
    steps:
      - name: Install jq tool
        uses: dcarbone/install-jq-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Az module
        run: Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser -Repository PSGallery
        shell: pwsh

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID" `
        shell: pwsh
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_PRINCIPAL_TYPE: ServicePrincipal

        # AZD deploy uses an AZD hook to execute the load test tool that will upload load test files
        # uploading the AZD load test requires a CLI login to authenticate
      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}

      - name: QA - Validate Deployment
        run: ./testscripts/call-validate-deployment.sh -g $resourceGroupName


  teardown:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:1.5.1
    env:
        AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ secrets.AZURE_LOCATION2 }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        IS_RUN_AS_SERVICEPRINCIPAL: true

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Log in with azd (Federated Credentials)
        run: |
          azd login  --client-id ${{ secrets.AZURE_CLIENT_ID }}  --federated-credential-provider "github"  --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure Dev Down
        run: azd down --force --purge --no-prompt
